apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing
spec:
  parallelism: 5
  template:
    spec:
      containers:
      - name: processor
        image: python:3.8
        command: ["python", "/scripts/process_data.py"]
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: OnFailure