apiVersion: batch/v1
kind: Job
metadata:
  name: web-server-health-check
spec:
  template:
    spec:
      containers:
      - name: check-web-server
        image: appropriate/curl
        command: ["curl", "-f", "http://my-web-service.default.svc.cluster.local"]
      restartPolicy: OnFailure